import{a as v,S as w,i as l}from"./assets/vendor-CRCB-GUD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();const f=async(e,t,a)=>{const o=new URLSearchParams({per_page:a,page:t,safesearch:"true",image_type:"photo",orientation:"horizontal",key:"45720835-cd950b20c56733b9244c71a24",q:e});return(await v.get(`https://pixabay.com/api/?${o}`)).data},L=e=>`<li class="gallery-item">
  <a class="img-link" href="${e.largeImageURL}">
  <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" width="360" height="200"/>
  </a>
  <div class="inf-box">
  <b class="img-prop">Likes: <span class="img-prop-value">${e.likes}</span></b>
  <b class="img-prop">Views: <span class="img-prop-value">${e.views}</span></b>
  <b class="img-prop">Comments: <span class="img-prop-value">${e.comments}</span></b>
  <b class="img-prop">Downloads: <span class="img-prop-value">${e.downloads}</span></b>
  </div>
  </li>`,S=(e,t)=>{t.innerHTML=e},q=e=>{e.innerHTML=""},b=new w(".gallery-item a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8}),p=document.querySelector(".form"),g=document.querySelector(".gallery"),c=document.querySelector("#load-more-loader-top"),u=document.querySelector(".gallery + button"),m=document.querySelector("#load-more-loader");console.log(u);let n=1,y=15,i="",h=!0;p.addEventListener("submit",async e=>{h||u.classList.remove("button-load-more"),n=1,e.preventDefault(),i=p.elements.user_query.value.trim(),q(g),c.classList.add("loader");try{const t=await f(i,n,y);if(t.total===0)return c.classList.remove("loader"),l.error({message:"Sorry, there are no images matching your search query. Please try again!"});const a=t.hits.map(o=>L(o)).join("");S(a,g),b.refresh(),c.classList.remove("loader"),u.classList.add("button-load-more")}catch(t){c.classList.remove("loader"),l.error({message:`Oops! Something went wrong. ${t}`})}m.classList.remove("loader"),h=!1});u.addEventListener("click",async()=>{if(i===""){l.error({message:"Please enter a subject for the photo"});return}m.classList.add("loader"),i=p.elements.user_query.value.trim();try{n+=1;const e=await f(i,n,y),t=e.hits.map(s=>L(s)).join(""),o=document.querySelector(".gallery-item").getBoundingClientRect().height;console.log(o*2);const r=Math.ceil(e.totalHits/y);if(n>r)return m.classList.remove("loader"),l.error({message:"We're sorry, but you've reached the end of search results."});g.insertAdjacentHTML("beforeend",t),m.classList.remove("loader"),b.refresh(),scrollBy({top:o*2,behavior:"smooth"})}catch(e){l.error({message:`Oops! Something went wrong. Erorr: ${e}`})}});
//# sourceMappingURL=index.js.map
