import{a as v,S as w,i}from"./assets/vendor-CRCB-GUD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const p of s.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&o(p)}).observe(document,{childList:!0,subtree:!0});function l(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=l(t);fetch(t.href,s)}})();const h=async(e,r,l)=>{const o=new URLSearchParams({per_page:l,page:r,safesearch:"true",image_type:"photo",orientation:"horizontal",key:"45720835-cd950b20c56733b9244c71a24",q:e});return(await v.get(`https://pixabay.com/api/?${o}`)).data},L=e=>`<li class="gallery-item">
  <a class="img-link" href="${e.largeImageURL}">
  <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" width="360" height="200"/>
  </a>
  <div class="inf-box">
  <b class="img-prop">Likes: <span class="img-prop-value">${e.likes}</span></b>
  <b class="img-prop">Views: <span class="img-prop-value">${e.views}</span></b>
  <b class="img-prop">Comments: <span class="img-prop-value">${e.comments}</span></b>
  <b class="img-prop">Downloads: <span class="img-prop-value">${e.downloads}</span></b>
  </div>
  </li>`,S=(e,r)=>{r.innerHTML=e},q=e=>{e.innerHTML=""},b=new w(".gallery-item a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8}),g=document.querySelector(".form"),y=document.querySelector(".gallery"),u=document.querySelector("#load-more-loader-top"),a=document.querySelector(".gallery + button"),m=document.querySelector("#load-more-loader");let n=1,d=15,c="",f=!0;g.addEventListener("submit",async e=>{f||a.classList.remove("js-button"),e.preventDefault(),c=g.elements.user_query.value.trim(),n=1,q(y),u.classList.add("loader");try{const r=await h(c,n,d);if(r.totalHits===0){u.classList.remove("loader"),i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}r.totalHits<=d&&(console.log("pipi"),console.log(r.totalHits),a.classList.remove("js-button"));const l=r.hits.map(o=>L(o)).join("");S(l,y),b.refresh(),u.classList.remove("loader"),a.classList.add("js-button")}catch(r){u.classList.remove("loader"),i.error({message:`Oops! Something went wrong. ${r}`})}m.classList.remove("loader"),f=!1});a.addEventListener("click",async()=>{if(a.classList.remove("js-button"),c===""){i.error({message:"Please enter a subject for the photo"});return}m.classList.add("loader"),c=g.elements.user_query.value.trim();try{n+=1;const e=await h(c,n,d),r=e.hits.map(s=>L(s)).join(""),o=document.querySelector(".gallery-item").getBoundingClientRect().height,t=Math.ceil(e.totalHits/d);if(n>t)return m.classList.remove("loader"),a.classList.remove("js-button"),i.error({message:"We're sorry, but you've reached the end of search results."});y.insertAdjacentHTML("beforeend",r),m.classList.remove("loader"),a.classList.add("js-button"),b.refresh(),scrollBy({top:o*2,behavior:"smooth"})}catch(e){i.error({message:`Oops! Something went wrong. Erorr: ${e}`})}});
//# sourceMappingURL=index.js.map
